### ISSUE TITLE
Allow api URL as source

### ISSUE THREAD

**Issue by marianbodisteanu** [LoveIsGrief/videojs-soundcloud#13]
Hi. Sometimes I need to play URLs from the soundcloud embed code.

If you check the iframe src it has a different URL structure that can be used as videojs source.

< iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/216846955&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true" >

I changed isSoundcloudUrl with the one below. Everything works.

videojs.Soundcloud.prototype.isSoundcloudUrl = function(url) {
  return /^(https?:\/\/)?(www.|api.)?soundcloud.com\//i.test(url);
};

**Comment by LoveIsGrief** [comment]
Hi!

Sorry for the late response. I'll have a look at this ASAP.

Cheers!
