### ISSUE TITLE
Most recent version not working

### ISSUE THREAD

**Issue by zenmatt** [LoveIsGrief/videojs-soundcloud#6]
Hi, I cannot get any version other than the code on the JSFiddle example working. I believe this is the first commit. Replacing the JSFiddle source with the most recent code and the previous commit fails (I did leave in the mandatory config stuff at the end).

In both my own app and the JSFiddle app, I am able to load soundcloud files successfully via the API with the code from your initial commit.

Any ideas?

**Comment by LoveIsGrief** [comment]
Closed with #10
